### ISSUE TITLE
Requested features for mpi-serial

### ISSUE THREAD

**Issue by rljacob** [MCSclimate/MCT#10]
@jedwards4b asks for the following features in mpi-serial

objects:
MPI_Info
MPI_Info_null
MPI_Offset

Types:
MPI_Long_Long
MPI_Unsigned_Long_long

functions:
MPI_Info_create
MPI_Info_set
MPI_Type_size
MPI_Type_Create_indexed_block
MPI_Alltoallw

Buffer address constants:
MPI_IN_PLACE

**Comment by rljacob** [comment]
MPI_INFO_NULL and MPI_OFFSET  are defined in mpif.h but not mpi.h

MPI_Type_size is defined in type.c but not in mpif.h or mpi.h.

**Comment by jedwards4b** [comment]
There is a difference between MPI_OFFSET and MPI_Offset in c

Is anyone working on these?   I'm just about ready to put pio2.0 into CESM
but the current mpi-serial would require a lot of ifdefs in the code that I
would rather not have to do.

On Mon, Mar 30, 2015 at 9:49 PM, Robert Jacob <notifications@github.com>
wrote:

> MPI_INFO_NULL and MPI_OFFSET are defined in mpif.h but not mpi.h
>
> MPI_Type_size is defined in type.c but not in mpif.h or mpi.h.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/MCSclimate/MCT/issues/10#issuecomment-87925620>.
>



-- 
Jim Edwards

CESM Software Engineer
National Center for Atmospheric Research
Boulder, CO

**Comment by rljacob** [comment]
No I think this is just a case of the code exists for these functions/constants but the .h files haven't been updated/synced.

**Comment by rljacob** [comment]
The above were all added as of f538fd5e8417418e6c391673f7ef43155a2faa01
