### ISSUE TITLE
Add MPI_Get_library_version to mpi-serial

### ISSUE THREAD

**Issue by rljacob** [MCSclimate/MCT#12]
Even though its an MPI 3.0 function, it would be very useful for identifying mpi-serial to other libraries, applications or configure systems.

Suggested by @quantheory.

**Comment by rloy** [comment]
I agree.

**Comment by rljacob** [comment]
Does that mean you'll implement it? :)

**Comment by rloy** [comment]
Yes.

**Comment by quantheory** [comment]
:dancer:

Once this is added I will update the CMake test.

**Comment by rloy** [comment]
Sean,

Were you hoping to have the string contain anything in particular?
e.g. is "mpi-serial" sufficient ? 

Ray

**Comment by quantheory** [comment]
I figured I'd leave it up to you. I think that any string that's unique to mpi-serial is fine, though you might also want to add a version number (e.g. "mpi-serial v2.0") just in case that becomes useful in the future).

**Comment by rloy** [comment]
I can hardcode the version like that but I don't know of an easy way to tie it
to the git version - open to suggestions.

**Comment by rljacob** [comment]
I don't think we need to worry about that.   It wouldn't help to link it to the hash so we just have to remember to update that string when a new version is tagged.

**Comment by rljacob** [comment]
@rloy, how is this coming along?

**Comment by rloy** [comment]
I added that a few weeks back. 

-Ray

**Comment by rloy** [comment]
https://github.com/MCSclimate/MCT/commit/4354ad6edabd94092ef0cc2c223fe88ec0854753

**Comment by rljacob** [comment]
Thanks!  I must have missed that message.

Issue fixed by 4354ad6edabd94092ef0cc2c223fe88ec0854753
