### ISSUE TITLE
nag compiler FCFLAGS is overwritten in mpi-serial configure 

### ISSUE THREAD

**Issue by jedwards4b** [MCSclimate/MCT#15]
At line 81 of configure.in the FCFLAGS variable is overwritten when you are using the nag fortran compiler.      We do not want to use this flag (-mismatch) with CESM and know how to avoid it.  We would prefer if this flag were only set if the user has not provided any FCFLAGS as input to configure.

**Comment by jedwards4b** [comment]
This solves the problem:
   if test -z "$FCFLAGS"; then
     FCFLAGS="-mismatch"
   fi

**Comment by rloy** [comment]
Makes sense, I made the change.

FWIW the compiler-specific code in the configure was originally copied
from MCT, in the effort to make mpi-serial stand-alone.


On May 4, 2015, at 3:35 PM, jedwards4b <notifications@github.com> wrote:

> This solves the problem:
> if test -z "$FCFLAGS"; then
> FCFLAGS="-mismatch"
> fi
>

**Comment by rljacob** [comment]
Fixed in 4964fec2d9d009e0981961606c5ceea0db423772
