### ISSUE TITLE
Possible problems with Rearranger at 100K procs

### ISSUE THREAD

**Issue by rljacob** [MCSclimate/MCT#30]
(copied from MCT's old bugzilla)

Reported by @worleyph
"There is communication logic in MCT that will probably break some day (see m_Rearranger), say when running on 100K or higher core counts. Posting 100K or more irecv requests before starting
the sends is likely to perform poorly or die. Flow control will help here as well, but the necessary modifications will be somewhat messier."

**Comment by rljacob** [comment]
If "AlltoAll" is true then Rearranger will use MPI_Alltoallv instead of posting a bunch of irecv/isend.

**Comment by worleyph** [comment]
Hi @rljacob , do you need any input from me? A long time ago I tried to add flow control, but I think that I could never get it debugged (in the time I had - this was a background investigation). There was also some issue with MPI_Alltoallv, but this was so long ago that it may no longer be relevant. Having compile-time selection of the communication protocol is inconvenient - see recent PIO1 work, so if there is not a runtime option to switch between the point-to-point and collective, I'd suggest adding such a capability. (Perhaps it is already there - I don't have the time to look right now.)

**Comment by rljacob** [comment]
No not right now.   AlltoAll is already runtime selectable.

**Comment by rljacob** [comment]
Fixed by importing the swapm version of MPI_AlltoallV from PIO in #38
